export const messageConstant = {
  LOAD_MSGS: 'LOAD_MSGS',
  LOAD_MSGS_SUCCESS: 'LOAD_MSGS_SUCCESS',
  LOAD_MSGS_ERROR: 'LOAD_MSGS_ERROR',
  ADD_MSGS_SUCCESS: 'ADD_MSGS_SUCCESS',
  ADD_MSGS_ERROR: 'ADD_MSGS_ERROR',
  DELETE_MSG_SUCCESS: 'DELETE_MSG_SUCCESS',
  DELETE_MSG_ERROR: 'DELETE_MSG_ERROR'
};

export const loginConstant = {
  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_ERROR: 'LOGIN_ERROR',
  VERIFY: 'VERIFY',
  VERIFY_SUCCESS: 'VERIFY_SUCCESS',
  VERIFY_ERROR: 'VERIFY_ERROR'
};