const LOAD_ARTICLES = 'LOAD_ARTICLES',
      LOAD_ARTICLES_SUCCESS = 'LOAD_ARTICLES_SUCCESS',
      LOAD_ARTICLES_ERROR = 'LOAD_ARTICLES_ERROR',
      ADD_ARTICLES_SUCCESS = 'ADD_ARTICLES_SUCCESS',
      ADD_ARTICLES_ERROR = 'ADD_ARTICLES_ERROR';

export {
  LOAD_ARTICLES,
  LOAD_ARTICLES_SUCCESS,
  LOAD_ARTICLES_ERROR,
  ADD_ARTICLES_SUCCESS,
  ADD_ARTICLES_ERROR
};