const LOAD_MSGS = 'LOAD_MSGS',
      LOAD_MSGS_SUCCESS = 'LOAD_MSGS_SUCCESS',
      LOAD_MSGS_ERROR = 'LOAD_MSGS_ERROR',
      ADD_MSGS_SUCCESS = 'ADD_MSGS_SUCCESS',
      ADD_MSGS_ERROR = 'ADD_MSGS_ERROR';

export {
  LOAD_MSGS,
  LOAD_MSGS_SUCCESS,
  LOAD_MSGS_ERROR,
  ADD_MSGS_SUCCESS,
  ADD_MSGS_ERROR
};